// Complete periodic table data for all 118 elements with correct positions
const all118Elements = [
    // Period 1
    {number: 1, symbol: 'H', name: 'Hydro', category: 'nonmetal', mass: '1.00784', position: [1, 1]},
    {number: 2, symbol: 'He', name: 'Heli', category: 'noble-gas', mass: '4.002602', position: [18, 1]},
    
    // Period 2
    {number: 3, symbol: 'Li', name: 'Liti', category: 'alkali-metal', mass: '6.94', position: [1, 2]},
    {number: 4, symbol: 'Be', name: 'Beri', category: 'alkaline-earth', mass: '9.0121831', position: [2, 2]},
    {number: 5, symbol: 'B', name: 'Bo', category: 'metalloid', mass: '10.81', position: [13, 2]},
    {number: 6, symbol: 'C', name: 'Cacbon', category: 'nonmetal', mass: '12.011', position: [14, 2]},
    {number: 7, symbol: 'N', name: 'Nitơ', category: 'nonmetal', mass: '14.007', position: [15, 2]},
    {number: 8, symbol: 'O', name: 'Oxy', category: 'nonmetal', mass: '15.999', position: [16, 2]},
    {number: 9, symbol: 'F', name: 'Flo', category: 'halogen', mass: '18.998403163', position: [17, 2]},
    {number: 10, symbol: 'Ne', name: 'Neon', category: 'noble-gas', mass: '20.1797', position: [18, 2]},

    // Period 3
    {number: 11, symbol: 'Na', name: 'Natri', category: 'alkali-metal', mass: '22.98976928', position: [1, 3]},
    {number: 12, symbol: 'Mg', name: 'Magie', category: 'alkaline-earth', mass: '24.305', position: [2, 3]},
    {number: 13, symbol: 'Al', name: 'Nhôm', category: 'post-transition', mass: '26.9815385', position: [13, 3]},
    {number: 14, symbol: 'Si', name: 'Silic', category: 'metalloid', mass: '28.085', position: [14, 3]},
    {number: 15, symbol: 'P', name: 'Phốt pho', category: 'nonmetal', mass: '30.973761998', position: [15, 3]},
    {number: 16, symbol: 'S', name: 'Lưu huỳnh', category: 'nonmetal', mass: '32.06', position: [16, 3]},
    {number: 17, symbol: 'Cl', name: 'Clo', category: 'halogen', mass: '35.45', position: [17, 3]},
    {number: 18, symbol: 'Ar', name: 'Argon', category: 'noble-gas', mass: '39.948', position: [18, 3]},

    // Period 4
    {number: 19, symbol: 'K', name: 'Kali', category: 'alkali-metal', mass: '39.0983', position: [1, 4]},
    {number: 20, symbol: 'Ca', name: 'Canxi', category: 'alkaline-earth', mass: '40.078', position: [2, 4]},
    {number: 21, symbol: 'Sc', name: 'Scandi', category: 'transition-metal', mass: '44.955908', position: [3, 4]},
    {number: 22, symbol: 'Ti', name: 'Titan', category: 'transition-metal', mass: '47.867', position: [4, 4]},
    {number: 23, symbol: 'V', name: 'Vanadi', category: 'transition-metal', mass: '50.9415', position: [5, 4]},
    {number: 24, symbol: 'Cr', name: 'Crom', category: 'transition-metal', mass: '51.9961', position: [6, 4]},
    {number: 25, symbol: 'Mn', name: 'Mangan', category: 'transition-metal', mass: '54.938044', position: [7, 4]},
    {number: 26, symbol: 'Fe', name: 'Sắt', category: 'transition-metal', mass: '55.845', position: [8, 4]},
    {number: 27, symbol: 'Co', name: 'Coban', category: 'transition-metal', mass: '58.933194', position: [9, 4]},
    {number: 28, symbol: 'Ni', name: 'Niken', category: 'transition-metal', mass: '58.6934', position: [10, 4]},
    {number: 29, symbol: 'Cu', name: 'Đồng', category: 'transition-metal', mass: '63.546', position: [11, 4]},
    {number: 30, symbol: 'Zn', name: 'Kẽm', category: 'transition-metal', mass: '65.38', position: [12, 4]},
    {number: 31, symbol: 'Ga', name: 'Gali', category: 'post-transition', mass: '69.723', position: [13, 4]},
    {number: 32, symbol: 'Ge', name: 'Gecmani', category: 'metalloid', mass: '72.630', position: [14, 4]},
    {number: 33, symbol: 'As', name: 'Asen', category: 'metalloid', mass: '74.921595', position: [15, 4]},
    {number: 34, symbol: 'Se', name: 'Selen', category: 'nonmetal', mass: '78.971', position: [16, 4]},
    {number: 35, symbol: 'Br', name: 'Brom', category: 'halogen', mass: '79.904', position: [17, 4]},
    {number: 36, symbol: 'Kr', name: 'Krypton', category: 'noble-gas', mass: '83.798', position: [18, 4]},

    // Period 5
    {number: 37, symbol: 'Rb', name: 'Rubiđi', category: 'alkali-metal', mass: '85.4678', position: [1, 5]},
    {number: 38, symbol: 'Sr', name: 'Stronti', category: 'alkaline-earth', mass: '87.62', position: [2, 5]},
    {number: 39, symbol: 'Y', name: 'Ytri', category: 'transition-metal', mass: '88.90584', position: [3, 5]},
    {number: 40, symbol: 'Zr', name: 'Zirconi', category: 'transition-metal', mass: '91.224', position: [4, 5]},
    {number: 41, symbol: 'Nb', name: 'Niobi', category: 'transition-metal', mass: '92.90637', position: [5, 5]},
    {number: 42, symbol: 'Mo', name: 'Molipđen', category: 'transition-metal', mass: '95.95', position: [6, 5]},
    {number: 43, symbol: 'Tc', name: 'Tecneti', category: 'transition-metal', mass: '98', position: [7, 5]},
    {number: 44, symbol: 'Ru', name: 'Ruteni', category: 'transition-metal', mass: '101.07', position: [8, 5]},
    {number: 45, symbol: 'Rh', name: 'Roði', category: 'transition-metal', mass: '102.90550', position: [9, 5]},
    {number: 46, symbol: 'Pd', name: 'Palađi', category: 'transition-metal', mass: '106.42', position: [10, 5]},
    {number: 47, symbol: 'Ag', name: 'Bạc', category: 'transition-metal', mass: '107.8682', position: [11, 5]},
    {number: 48, symbol: 'Cd', name: 'Cadimi', category: 'transition-metal', mass: '112.414', position: [12, 5]},
    {number: 49, symbol: 'In', name: 'Inđi', category: 'post-transition', mass: '114.818', position: [13, 5]},
    {number: 50, symbol: 'Sn', name: 'Thiếc', category: 'post-transition', mass: '118.710', position: [14, 5]},
    {number: 51, symbol: 'Sb', name: 'Antimon', category: 'metalloid', mass: '121.760', position: [15, 5]},
    {number: 52, symbol: 'Te', name: 'Telua', category: 'metalloid', mass: '127.60', position: [16, 5]},
    {number: 53, symbol: 'I', name: 'Iot', category: 'halogen', mass: '126.90447', position: [17, 5]},
    {number: 54, symbol: 'Xe', name: 'Xenon', category: 'noble-gas', mass: '131.293', position: [18, 5]},

    // Period 6
    {number: 55, symbol: 'Cs', name: 'Xezi', category: 'alkali-metal', mass: '132.9054519', position: [1, 6]},
    {number: 56, symbol: 'Ba', name: 'Bari', category: 'alkaline-earth', mass: '137.327', position: [2, 6]},
    {number: 57, symbol: 'La', name: 'Lantan', category: 'lanthanide', mass: '138.90547', position: [3, 6]},
    {number: 58, symbol: 'Ce', name: 'Xeri', category: 'lanthanide', mass: '140.116', position: [4, 9]},
    {number: 59, symbol: 'Pr', name: 'Praseođim', category: 'lanthanide', mass: '140.90766', position: [5, 9]},
    {number: 60, symbol: 'Nd', name: 'Neođim', category: 'lanthanide', mass: '144.242', position: [6, 9]},
    {number: 61, symbol: 'Pm', name: 'Prometi', category: 'lanthanide', mass: '145', position: [7, 9]},
    {number: 62, symbol: 'Sm', name: 'Samari', category: 'lanthanide', mass: '150.36', position: [8, 9]},
    {number: 63, symbol: 'Eu', name: 'Europi', category: 'lanthanide', mass: '151.964', position: [9, 9]},
    {number: 64, symbol: 'Gd', name: 'Gadolini', category: 'lanthanide', mass: '157.25', position: [10, 9]},
    {number: 65, symbol: 'Tb', name: 'Terbi', category: 'lanthanide', mass: '158.92535', position: [11, 9]},
    {number: 66, symbol: 'Dy', name: 'Đysprosi', category: 'lanthanide', mass: '162.500', position: [12, 9]},
    {number: 67, symbol: 'Ho', name: 'Holmi', category: 'lanthanide', mass: '164.93033', position: [13, 9]},
    {number: 68, symbol: 'Er', name: 'Erbi', category: 'lanthanide', mass: '167.259', position: [14, 9]},
    {number: 69, symbol: 'Tm', name: 'Tuli', category: 'lanthanide', mass: '168.93422', position: [15, 9]},
    {number: 70, symbol: 'Yb', name: 'Yterbi', category: 'lanthanide', mass: '173.045', position: [16, 9]},
    {number: 71, symbol: 'Lu', name: 'Luteti', category: 'lanthanide', mass: '174.9668', position: [17, 9]},
    {number: 72, symbol: 'Hf', name: 'Hafni', category: 'transition-metal', mass: '178.49', position: [4, 6]},
    {number: 73, symbol: 'Ta', name: 'Tantal', category: 'transition-metal', mass: '180.94788', position: [5, 6]},
    {number: 74, symbol: 'W', name: 'Vonfram', category: 'transition-metal', mass: '183.84', position: [6, 6]},
    {number: 75, symbol: 'Re', name: 'Reni', category: 'transition-metal', mass: '186.207', position: [7, 6]},
    {number: 76, symbol: 'Os', name: 'Osmi', category: 'transition-metal', mass: '190.23', position: [8, 6]},
    {number: 77, symbol: 'Ir', name: 'Iriđi', category: 'transition-metal', mass: '192.217', position: [9, 6]},
    {number: 78, symbol: 'Pt', name: 'Platin', category: 'transition-metal', mass: '195.084', position: [10, 6]},
    {number: 79, symbol: 'Au', name: 'Vàng', category: 'transition-metal', mass: '196.966569', position: [11, 6]},
    {number: 80, symbol: 'Hg', name: 'Thủy ngân', category: 'transition-metal', mass: '200.592', position: [12, 6]},
    {number: 81, symbol: 'Tl', name: 'Tali', category: 'post-transition', mass: '204.38', position: [13, 6]},
    {number: 82, symbol: 'Pb', name: 'Chì', category: 'post-transition', mass: '207.2', position: [14, 6]},
    {number: 83, symbol: 'Bi', name: 'Bismut', category: 'post-transition', mass: '208.98040', position: [15, 6]},
    {number: 84, symbol: 'Po', name: 'Poloni', category: 'post-transition', mass: '209', position: [16, 6]},
    {number: 85, symbol: 'At', name: 'Astatin', category: 'halogen', mass: '210', position: [17, 6]},
    {number: 86, symbol: 'Rn', name: 'Radon', category: 'noble-gas', mass: '222', position: [18, 6]},

    // Period 7
    {number: 87, symbol: 'Fr', name: 'Franxi', category: 'alkali-metal', mass: '223', position: [1, 7]},
    {number: 88, symbol: 'Ra', name: 'Raði', category: 'alkaline-earth', mass: '226', position: [2, 7]},
    {number: 89, symbol: 'Ac', name: 'Actini', category: 'actinide', mass: '227', position: [3, 7]},
    {number: 90, symbol: 'Th', name: 'Thori', category: 'actinide', mass: '232.0377', position: [4, 10]},
    {number: 91, symbol: 'Pa', name: 'Protactini', category: 'actinide', mass: '231.03588', position: [5, 10]},
    {number: 92, symbol: 'U', name: 'Urani', category: 'actinide', mass: '238.02891', position: [6, 10]},
    {number: 93, symbol: 'Np', name: 'Neptuni', category: 'actinide', mass: '237', position: [7, 10]},
    {number: 94, symbol: 'Pu', name: 'Plutoni', category: 'actinide', mass: '244', position: [8, 10]},
    {number: 95, symbol: 'Am', name: 'Americi', category: 'actinide', mass: '243', position: [9, 10]},
    {number: 96, symbol: 'Cm', name: 'Curi', category: 'actinide', mass: '247', position: [10, 10]},
    {number: 97, symbol: 'Bk', name: 'Berkeli', category: 'actinide', mass: '247', position: [11, 10]},
    {number: 98, symbol: 'Cf', name: 'Californi', category: 'actinide', mass: '251', position: [12, 10]},
    {number: 99, symbol: 'Es', name: 'Einsteini', category: 'actinide', mass: '252', position: [13, 10]},
    {number: 100, symbol: 'Fm', name: 'Fermi', category: 'actinide', mass: '257', position: [14, 10]},
    {number: 101, symbol: 'Md', name: 'Mendelevi', category: 'actinide', mass: '258', position: [15, 10]},
    {number: 102, symbol: 'No', name: 'Nobeli', category: 'actinide', mass: '259', position: [16, 10]},
    {number: 103, symbol: 'Lr', name: 'Lorenxi', category: 'actinide', mass: '266', position: [17, 10]},
    {number: 104, symbol: 'Rf', name: 'Rutherfordi', category: 'transition-metal', mass: '267', position: [4, 7]},
    {number: 105, symbol: 'Db', name: 'Dubni', category: 'transition-metal', mass: '268', position: [5, 7]},
    {number: 106, symbol: 'Sg', name: 'Seaborgi', category: 'transition-metal', mass: '269', position: [6, 7]},
    {number: 107, symbol: 'Bh', name: 'Bohri', category: 'transition-metal', mass: '270', position: [7, 7]},
    {number: 108, symbol: 'Hs', name: 'Hassi', category: 'transition-metal', mass: '277', position: [8, 7]},
    {number: 109, symbol: 'Mt', name: 'Meitneri', category: 'transition-metal', mass: '278', position: [9, 7]},
    {number: 110, symbol: 'Ds', name: 'Darmstadti', category: 'transition-metal', mass: '281', position: [10, 7]},
    {number: 111, symbol: 'Rg', name: 'Roentgeni', category: 'transition-metal', mass: '282', position: [11, 7]},
    {number: 112, symbol: 'Cn', name: 'Copernici', category: 'transition-metal', mass: '285', position: [12, 7]},
    {number: 113, symbol: 'Nh', name: 'Nihoni', category: 'post-transition', mass: '286', position: [13, 7]},
    {number: 114, symbol: 'Fl', name: 'Flerovi', category: 'post-transition', mass: '289', position: [14, 7]},
    {number: 115, symbol: 'Mc', name: 'Moscovi', category: 'post-transition', mass: '290', position: [15, 7]},
    {number: 116, symbol: 'Lv', name: 'Livermori', category: 'post-transition', mass: '293', position: [16, 7]},
    {number: 117, symbol: 'Ts', name: 'Tennessi', category: 'halogen', mass: '294', position: [17, 7]},
    {number: 118, symbol: 'Og', name: 'Oganeson', category: 'noble-gas', mass: '294', position: [18, 7]}
];

// Export for use in other files
export { all118Elements };
